apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: postgres
  POSTGRES_URL: jdbc:postgresql://postgresql.ns-data.svc.cluster.local:5432/petclinic
