apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      tolerations:
        - key: "cloud"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: petclinic
          matchLabelKeys:
            - pod-template-hash

      containers:
        - name: petclinic
          image: 10.0.0.3:30050/petclinic/petclinic:0.3.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
          

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres

            - name: POSTGRES_URL
              value: jdbc:postgresql://postgresql.ns-data.svc.cluster.local:5432/petclinic

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: POSTGRES_USER

            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: POSTGRES_PASS

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
spec:
  selector:
    app: petclinic
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  namespace: petclinic
spec:
  ingressClassName: traefik
  rules:
    - host: petclinic.devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic
                port:
                  number: 80
