apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petclinic
  namespace: petclinic
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: petclinic
